/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_0_FUNC_ALT2 0x02u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_0_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_18_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_19_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_19_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_20_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_20_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_21_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO0_21_MODE_PULL_DOWN 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_23_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_23_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_23_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_28_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_28_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_29_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_29_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_2_FUNC_ALT1 0x01u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_2_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_30_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_3_FUNC_ALT1 0x01u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_3_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_6_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_1_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_2_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO1_2_MODE_PULL_DOWN 0x01u

/*! @name PIO1_2 (number 41), SW_ACC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW_ACC_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW_ACC_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SW_ACC_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_ACC_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_ACC_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO0_28 (number 44), SW_BRAKE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW_BRAKE_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW_BRAKE_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SW_BRAKE_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_BRAKE_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_BRAKE_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_20 (number 48), SW_DEBRAKE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW_DEBRAKE_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW_DEBRAKE_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SW_DEBRAKE_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_DEBRAKE_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_DEBRAKE_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO0_23 (number 12), SW_AUTOHOLD
  @{ */
#define BOARD_INITPINS_SW_AUTOHOLD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_AUTOHOLD_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_AUTOHOLD_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO1_1 (number 39), LED_AUTO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_AUTO_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_AUTO_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_AUTO_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_AUTO_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_AUTO_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_18 (number 38), LED_BRAKE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BRAKE_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BRAKE_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_BRAKE_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BRAKE_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BRAKE_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_19 (number 58), MOTOR_FWD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTOR_FWD_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTOR_FWD_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_MOTOR_FWD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_FWD_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_FWD_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_6 (number 57), MOTOR_REV
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTOR_REV_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTOR_REV_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_MOTOR_REV_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_REV_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_REV_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_21 (number 49), SW_PEDAL_BRAKE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW_PEDAL_BRAKE_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW_PEDAL_BRAKE_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SW_PEDAL_BRAKE_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_PEDAL_BRAKE_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_PEDAL_BRAKE_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
